### ISSUE TITLE
Alma Prox Attack

### ISSUE THREAD

**Issue by asparius** [jeromerony/alma_prox_segmentation#1]
Alma_prox attack does not work with current version of adv_lib version. Some of the arguments like "norm" and "prox" are not in the attack function from adv_lib. Additionally, alma_prox_linf is not in defined attacks so the given attack example crashes. Lastly, it only works in mmsegmentation 0.24.1.

**Comment by jeromerony** [comment]
Hi!
These arguments correspond to an older version ; the initial version of the paper was for $\ell_1$, $\ell_2$ and  $\ell_\infty$ norms. Same for `alma_prox_linf`. I fixed these references.
For MMSegmentation, I don't have control there, I can only make sure one version works.

**Comment by asparius** [comment]
Thanks for the response. Perhaps you can add mmsegmentation version in the dependency file and add the version tag in cloning of the library.

**Comment by jeromerony** [comment]
I just updated everything to mmseg 1.2.2. I checked that things were working properly by attacking a few images. However, I cannot vouch that the performance will be exactly the same, since the experiments are quite costly to redo.
Let me know if things become weird with this version of 1.2.2 :)
